// SPDX-License-Identifier: MIT
// Copyright (c) 2018-2023, Advanced Micro Devices, Inc. All rights reserved.
#define ENABLE_CONV_FACTORY 1

#include "ck/tensor_operation/gpu/device/impl/device_grouped_conv_bwd_data_multiple_d_xdl_cshuffle_v1.hpp"
#include "common.hpp"

using OutDataType      = FP16;
using WeiDataType      = FP16;
using AccDataType      = FP32;
using CShuffleDataType = FP16;
using DsDataType       = ck::Tuple<>;
using InDataType       = FP16;

using OutLayout = ck::tensor_layout::convolution::NGKHW;
using WeiLayout = ck::tensor_layout::convolution::GKYXC;
using DsLayout  = ck::Tuple<>;
using InLayout  = ck::tensor_layout::convolution::NGCHW;

using OutElementOp = PassThrough;
using WeiElementOp = PassThrough;
using InElementOp  = PassThrough;

#if !defined(ENABLE_CONV_FACTORY)
// clang-format off
using DeviceConvInstance = ck::tensor_operation::device::DeviceGroupedConvBwdDataMultipleD_Xdl_CShuffle_v1
// ######| NDimSpatial|   ALayout|   BLayout|   DsLayout|  ELayout|       AData|       BData|     AccData|         CShuffle|       DsData|      EData| AElementwise| BElementwise| CDEElementwise| ConvolutionBackward| DoPad| DoPad|      NumGemmK| Block|  MPer|  NPer|  KPer| AK1| BK1| MPer| NPer|    MXdl|    NXdl|    ABlockTransfer| ABlockTransfer| ABlockTransfer| ABlockTransfer| ABlockTransfer| ABlockTransfer| ABlockLds|    BBlockTransfer| BBlockTransfer| BBlockTransfer| BBlockTransfer| BBlockTransfer| BBlockTransfer| BBlockLds| CShuffleMXdl| CShuffleNXdl|   CDEBlockTransfer| CDEBlockTransfer|
// ######|            |          |          |           |         |        Type|        Type|        Type|         DataType|         Type|       Type|    Operation|    Operation|      Operation|  DataSpecialization| GemmM| GemmN| PrefetchStage|  Size| Block| Block| Block|    |    |  XDL|  XDL| PerWave| PerWave|     ThreadCluster|  ThreadCluster| SrcAccessOrder|   SrcVectorDim|      SrcScalar|      DstScalar|    ExtraM|     ThreadCluster|  ThreadCluster| SrcAccessOrder|   SrcVectorDim|      SrcScalar|      DstScalar|    ExtraN|      PerWave|      PerWave|  _MBlock_MPerBlock|  ScalarPerVector|
// ######|            |          |          |           |         |            |            |            |                 |             |           |             |             |               |                    |      |      |              |      |      |      |      |    |    |     |     |        |        | Lengths_AK0_M_AK1|   ArrangeOrder|               |               |      PerVector|  PerVector_AK1|          | Lengths_BK0_N_BK1|   ArrangeOrder|               |               |      PerVector|  PerVector_BK1|          |   PerShuffle|   PerShuffle|  _NBlock_NPerBlock|       _NPerBlock|
// ######|            |          |          |           |         |            |            |            |                 |             |           |             |             |               |                    |      |      |              |      |      |      |      |    |    |     |     |        |        |                  |               |               |               |               |               |          |                  |               |               |               |               |               |          |             |             |                   |                 |
           < NDimSpatial, OutLayout, WeiLayout,   DsLayout, InLayout, OutDataType, WeiDataType, AccDataType, CShuffleDataType,   DsDataType, InDataType, OutElementOp, WeiElementOp,    InElementOp,  ConvBwdDataDefault,  true,  true,            1,   256,   256,   128,    32,   8,   8,   32,   32,       4,       2,     S<4, 64, 1>,       S<0, 2, 1>,     S<0, 2, 1>,              1,              4,              8,         1,       S<4, 64, 1>,     S<0, 2, 1>,     S<0, 2, 1>,              1,              2,              8,         1,            1,            1,     S<1, 32, 1, 8>,               8>;

// clang-format on
#else

using ALayout = OutLayout;
using BLayout = WeiLayout;
using ELayout = InLayout;
using F16 = FP16;
using F32 = FP32;
using Empty_Tuple = ck::Tuple<>;
static constexpr auto ConvSpec = ConvBwdDataDefault;

using DeviceConvBwdFactory = std::tuple<
  //ck::tensor_operation::device::DeviceGroupedConvBwdDataMultipleD_Xdl_CShuffle_v1< NDimSpatial, OutLayout, WeiLayout,   DsLayout, InLayout, OutDataType, WeiDataType, AccDataType, CShuffleDataType,   DsDataType, InDataType, OutElementOp, WeiElementOp,    InElementOp,  ConvBwdDataDefault,  true,  true,            1,   256,   256,   128,    32,   8,   8,   32,   32,       4,       2,     S<4, 64, 1>,       S<0, 2, 1>,     S<0, 2, 1>,              1,              4,              8,         1,       S<4, 64, 1>,     S<0, 2, 1>,     S<0, 2, 1>,              1,              2,              8,         1,            1,            1,     S<1, 32, 1, 8>,               8>

  // clang-format off
  // ######| NDimSpatial|   ALayout|   BLayout|   DsLayout|  ELayout|       AData|       BData|     AccData|         CShuffle|       DsData|      EData| AElementwise| BElementwise| CDEElementwise| ConvolutionBackward| DoPad| DoPad|                         NumGemmK| Block|  MPer|  NPer|  KPer| AK1| BK1| MPer| NPer|    MXdl|    NXdl|    ABlockTransfer| ABlockTransfer| ABlockTransfer| ABlockTransfer| ABlockTransfer| ABlockTransfer| ABlockLds|    BBlockTransfer| BBlockTransfer| BBlockTransfer| BBlockTransfer| BBlockTransfer| BBlockTransfer| BBlockLds| CShuffleMXdl| CShuffleNXdl|   CDEBlockTransfer| CDEBlockTransfer|
 //  ######|            |          |          |           |         |        Type|        Type|        Type|         DataType|         Type|       Type|    Operation|    Operation|      Operation|  DataSpecialization| GemmM| GemmN|                    PrefetchStage|  Size| Block| Block| Block|    |    |  XDL|  XDL| PerWave| PerWave|     ThreadCluster|  ThreadCluster| SrcAccessOrder|   SrcVectorDim|      SrcScalar|      DstScalar|    ExtraM|     ThreadCluster|  ThreadCluster| SrcAccessOrder|   SrcVectorDim|      SrcScalar|      DstScalar|    ExtraN|      PerWave|      PerWave|  _MBlock_MPerBlock|  ScalarPerVector|
 //  ######|            |          |          |           |         |            |            |            |                 |             |           |             |             |               |                    |      |      |                                 |      |      |      |      |    |    |     |     |        |        | Lengths_AK0_M_AK1|   ArrangeOrder|               |               |      PerVector|  PerVector_AK1|          | Lengths_BK0_N_BK1|   ArrangeOrder|               |               |      PerVector|  PerVector_BK1|          |   PerShuffle|   PerShuffle|  _NBlock_NPerBlock|       _NPerBlock|
 //  ######|            |          |          |           |         |            |            |            |                 |             |           |             |             |               |                    |      |      |                                 |      |      |      |      |    |    |     |     |        |        |                  |               |               |               |               |               |          |                  |               |               |               |               |               |          |             |             |                   |                 |
     //                                                                            NDimSpatial, ALayout, BLayout,    DsLayout, ELayout,   F16,   F16,     F32,      F16, Empty_Tuple,   F16,  PassThrough,  PassThrough,    PassThrough,            ConvSpec,  true,  true,             1
         ck::tensor_operation::device::DeviceGroupedConvBwdDataMultipleD_Xdl_CShuffle_v1<NDimSpatial,ALayout,BLayout,    DsLayout,ELayout,   F16,   F16,     F32,      F16,    Empty_Tuple,   F16, PassThrough, PassThrough, OutElementOp,       ConvSpec, true,  true,        1,  256,   128,   128,    32,   8,   8,   32,   32,    2,    2,     S<4, 64, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              2,             8,         1,     S<4, 64, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              2,              8,         1,           1,           1,               S<1, 32, 1, 8>,              4>
        ,ck::tensor_operation::device::DeviceGroupedConvBwdDataMultipleD_Xdl_CShuffle_v1<NDimSpatial,ALayout,BLayout,    DsLayout,ELayout,   F16,   F16,     F32,      F16,    Empty_Tuple,   F16, PassThrough, PassThrough, OutElementOp,       ConvSpec, true,  true,        1,  256,   128,   128,    32,   8,   8,   32,   32,    2,    2,     S<4, 64, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              2,             8,         1,     S<4, 64, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              2,              8,         1,           1,           1,               S<1, 32, 1, 8>,              8>
        ,ck::tensor_operation::device::DeviceGroupedConvBwdDataMultipleD_Xdl_CShuffle_v1<NDimSpatial,ALayout,BLayout,    DsLayout,ELayout,   F16,   F16,     F32,      F16,    Empty_Tuple,   F16, PassThrough, PassThrough, OutElementOp,       ConvSpec, true,  true,        1,  128,   128,    64,    32,   8,   8,   32,   32,    2,    2,     S<4, 32, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              4,             8,         1,     S<4, 32, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              2,              8,         1,           1,           1,               S<1, 16, 1, 8>,              4>
        ,ck::tensor_operation::device::DeviceGroupedConvBwdDataMultipleD_Xdl_CShuffle_v1<NDimSpatial,ALayout,BLayout,    DsLayout,ELayout,   F16,   F16,     F32,      F16,    Empty_Tuple,   F16, PassThrough, PassThrough, OutElementOp,       ConvSpec, true,  true,        1,  256,   128,    64,    32,   8,   8,   32,   32,    2,    1,     S<4, 64, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              2,             8,         1,     S<4, 64, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              1,              8,         1,           1,           1,               S<1, 32, 1, 8>,              8>
        ,ck::tensor_operation::device::DeviceGroupedConvBwdDataMultipleD_Xdl_CShuffle_v1<NDimSpatial,ALayout,BLayout,    DsLayout,ELayout,   F16,   F16,     F32,      F16,    Empty_Tuple,   F16, PassThrough, PassThrough, OutElementOp,       ConvSpec, true,  true,        1,  128,   64,    128,    32,   8,   8,   32,   32,    2,    2,     S<4, 32, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              2,             8,         1,     S<4, 32, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              4,              8,         1,           1,           1,               S<1, 16, 1, 8>,              4>  
        ,ck::tensor_operation::device::DeviceGroupedConvBwdDataMultipleD_Xdl_CShuffle_v1<NDimSpatial,ALayout,BLayout,    DsLayout,ELayout,   F16,   F16,     F32,      F16,    Empty_Tuple,   F16, PassThrough, PassThrough, OutElementOp,       ConvSpec, true,  true,        1,  256,   128,    64,    32,   8,   8,   32,   32,    2,    1,     S<4, 64, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              2,             8,         1,     S<4, 64, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              1,              8,         1,           1,           1,               S<1, 32, 1, 8>,              4>
        ,ck::tensor_operation::device::DeviceGroupedConvBwdDataMultipleD_Xdl_CShuffle_v1<NDimSpatial,ALayout,BLayout,    DsLayout,ELayout,   F16,   F16,     F32,      F16,    Empty_Tuple,   F16, PassThrough, PassThrough, OutElementOp,       ConvSpec, true,  true,        1,  256,   64,    128,    32,   8,   8,   32,   32,    1,    2,     S<4, 64, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              1,             8,         1,     S<4, 64, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              2,              8,         1,           1,           1,               S<1, 32, 1, 8>,              4>
        ,ck::tensor_operation::device::DeviceGroupedConvBwdDataMultipleD_Xdl_CShuffle_v1<NDimSpatial,ALayout,BLayout,    DsLayout,ELayout,   F16,   F16,     F32,      F16,    Empty_Tuple,   F16, PassThrough, PassThrough, OutElementOp,       ConvSpec, true,  true,        1,  128,   128,    32,    32,   8,   8,   32,   32,    2,    1,     S<4, 32, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              4,             8,         1,     S<4, 32, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              1,              8,         1,           1,           1,               S<1, 16, 1, 8>,              4>
        ,ck::tensor_operation::device::DeviceGroupedConvBwdDataMultipleD_Xdl_CShuffle_v1<NDimSpatial,ALayout,BLayout,    DsLayout,ELayout,   F16,   F16,     F32,      F16,    Empty_Tuple,   F16, PassThrough, PassThrough, OutElementOp,       ConvSpec, true,  true,        1,  128,   128,    32,    32,   8,   8,   32,   32,    2,    1,     S<4, 32, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              4,             8,         1,     S<4, 32, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              1,              8,         1,           1,           1,               S<1, 16, 1, 8>,              8>
        ,ck::tensor_operation::device::DeviceGroupedConvBwdDataMultipleD_Xdl_CShuffle_v1<NDimSpatial,ALayout,BLayout,    DsLayout,ELayout,   F16,   F16,     F32,      F16,    Empty_Tuple,   F16, PassThrough, PassThrough, OutElementOp,       ConvSpec, true,  true,        1,  256,   128,    64,    32,   8,   8,   16,   16,    4,    2,     S<4, 64, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              2,             8,         1,     S<4, 64, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              1,              8,         1,           1,           1,               S<1, 32, 1, 8>,              4>
        ,ck::tensor_operation::device::DeviceGroupedConvBwdDataMultipleD_Xdl_CShuffle_v1<NDimSpatial,ALayout,BLayout,    DsLayout,ELayout,   F16,   F16,     F32,      F16,    Empty_Tuple,   F16, PassThrough, PassThrough, OutElementOp,       ConvSpec, true,  true,        1,  256,   128,   128,    32,   8,   8,   32,   32,    2,    2,     S<4, 64, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              2,             8,         1,     S<4, 64, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              2,              8,         1,           1,           1,               S<1, 8, 1, 32>,              2>

        ,ck::tensor_operation::device::DeviceGroupedConvBwdDataMultipleD_Xdl_CShuffle_v1<NDimSpatial,ALayout,BLayout,    DsLayout,ELayout,   F16,   F16,     F32,      F16,    Empty_Tuple,   F16, PassThrough, PassThrough, OutElementOp,       ConvSpec, true,  true,        1,  256,   64,    128,    32,   8,   8,   32,   32,    1,    2,     S<4, 64, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              1,             8,         1,     S<4, 64, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              2,              8,         1,           1,           1,               S<1, 32, 1, 8>,              1>
        ,ck::tensor_operation::device::DeviceGroupedConvBwdDataMultipleD_Xdl_CShuffle_v1<NDimSpatial,ALayout,BLayout,    DsLayout,ELayout,   F16,   F16,     F32,      F16,    Empty_Tuple,   F16, PassThrough, PassThrough, OutElementOp,       ConvSpec, true,  true,        1,  64,    64,     32,    32,   8,   8,   32,   32,    2,    1,     S<4, 16, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              1,             8,         1,     S<4, 16, 1>,     S<0, 2, 1>,     S<0, 2, 1>, 1,              1,              8,         1,           1,           1,               S<1, 8, 1, 8>,               1>   
>;

#include "run_grouped_conv_bwd_data_example.inc"

int main(int argc, char* argv[]) { return run_grouped_conv_bwd_data_example(argc, argv); }
